name: Test Action

on: push
  
jobs:
  test-livecheck-tap:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Wait
        run: sleep 30
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          message: |
            First line
            SECOND LINE
          tap: dawidd6/test
          force: true
          livecheck: true
